name: Sync Image

on:
  workflow_dispatch:
    inputs:
      src_image:
        required: true
        description: "源镜像"
      des_tag:
        required: true
        description: 目标镜像名版本，完整镜像名: registry.cn-hangzhou.aliyuncs.com/jaign-mirror/default:[tag]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_ACR_USERNAME }}
          password: ${{ secrets.ALIYUN_ACR_PASSWORD }}
      - name: Copy
        id: copy
        uses: nick-fields/retry@v2.8.2
        with:
          timeout_minutes: 360
          max_attempts: 10
          command: |
            podman run \
              -v ~/.docker/config.json:/auth.json:ro \
              docker://quay.io/skopeo/stable:latest copy \
              --retry-times 10 \
              --authfile /auth.json \
              --multi-arch all \
              docker://${{ inputs.src_image }} \
              docker://registry.cn-hangzhou.aliyuncs.com/jaign-mirror/default:${{ inputs.des_tag }}
      - name: Report
        run: |
          echo "Total attempts: ${{ steps.copy.outputs.total_attempts }}"
