name: Sync devcontainer images

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Manual Run Workflow'
        required: true
        default: 'production'

jobs:
  sync:
    strategy:
      fail-fast: false
      matrix:
       repo:
       - base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_ACR_USERNAME }}
          password: ${{ secrets.ALIYUN_ACR_PASSWORD }}
      - name: Sync
        id: sync
        uses: nick-fields/retry@v2.8.2
        with:
          timeout_minutes: 360
          max_attempts: 10
          command: |
            podman run \
              -v ~/.docker/config.json:/auth.json:ro \
              docker://quay.io/skopeo/stable:v1.10.0 sync \
              --all \
              --retry-times 10 \
              --authfile /auth.json \
              --src docker \
              --dest docker \
              mcr.microsoft.com/devcontainers/${{ matrix.repo }} \
              registry.cn-hangzhou.aliyuncs.com/jaign/devcontainers
      - name: Report
        run: |
          echo "Total attempts: ${{ steps.sync.outputs.total_attempts }}"
